version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '08:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - 'dependencies'
