#!/bin/sh

docker pull zricethezav/gitleaks:latest
docker run --name gitleaks-filmotheque-front -v $(pwd):/service zricethezav/gitleaks protect --verbose --redact --staged --source=/service
docker rm gitleaks-filmotheque-front